/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RepresentationTheory.Symmetric.Specht.Ideal.Irreducible
public import TauCeti.RepresentationTheory.Symmetric.Specht.SubmoduleTheorem

/-!
# Comparing the two Specht-module presentations

The Specht module of a Young diagram has two constructions in this library.  It is the span of
the polytabloids inside the Young permutation module, and it is the left ideal generated by the
Young symmetrizer in the rational group algebra.  This file identifies those constructions for
the convention fixed throughout the symmetric-group development:

* the permutation module is a left module on left cosets;
* the polytabloid is `e_t = b_t · {t}`;
* the Young symmetrizer is `c_t = a_t b_t`; and
* the ideal is the left ideal `ℚ[Sₙ] c_t`.

An element of the ideal acts on the tabloid `{t}`, giving an intertwining map into the
polytabloid Specht module.  The map is nonzero: the coefficient of `{t}` in `c_t · {t}` is the
order of the row group.  Both sides are irreducible, so this intertwiner is an equivalence.

## Main results

* `TauCeti.YoungTableau.spechtIdealToSubrepresentation`: the canonical intertwining map from
  `ℚ[Sₙ] c_t` to the polytabloid Specht module.
* `TauCeti.YoungTableau.spechtIdealEquivSpechtSubrepresentation`: the resulting equivalence of
  representations.
* `TauCeti.YoungTableau.spechtIdealIsoSpechtSubrepresentation`: the categorical isomorphism of
  `Rep ℚ (Equiv.Perm (Fin μ.card))` objects.

## References

* [G. D. James, *The Representation Theory of the Symmetric Groups*][james1978], Chapters 3--4.
* [Schur--Weyl roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 3, “Polytabloids and the Specht module”.
-/

public section

namespace TauCeti

open scoped BigOperators

namespace YoungTableau

variable {μ : YoungDiagram}

noncomputable section

private abbrev permutationRep (μ : YoungDiagram) :=
  (permutationModule (shapePartition μ)).ρ

/-- The Young symmetrizer sends its tableau's tabloid into the polytabloid Specht module. -/
private theorem youngSymmetrizer_tabloid_mem (t : YoungTableau μ) :
    (permutationRep μ).asAlgebraHom (youngSymmetrizer t)
        (MonoidAlgebra.single (tabloid t) 1) ∈ spechtSubrepresentation μ := by
  rw [youngSymmetrizer_def, map_mul, Module.End.mul_apply, ← polytabloid_def]
  exact Representation.asAlgebraHom_mem_of_forall_mem _
    (spechtSubrepresentation μ).toSubmodule
    (fun g _ hx => (spechtSubrepresentation μ).apply_mem_toSubmodule g hx)
    _ (polytabloid_mem_spechtSubrepresentation t) (rowSymmetrizer t)

/-- Every element of the Young-symmetrizer ideal sends `{t}` into the polytabloid Specht
module. -/
private theorem spechtIdeal_apply_tabloid_mem (t : YoungTableau μ) (x : spechtIdeal t) :
    (permutationRep μ).asAlgebraHom (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
        (MonoidAlgebra.single (tabloid t) 1) ∈ spechtSubrepresentation μ := by
  obtain ⟨a, ha⟩ := (mem_spechtIdeal_iff t x).mp x.property
  rw [← ha, map_mul, Module.End.mul_apply]
  exact Representation.asAlgebraHom_mem_of_forall_mem _
    (spechtSubrepresentation μ).toSubmodule
    (fun g _ hx => (spechtSubrepresentation μ).apply_mem_toSubmodule g hx)
    _ (youngSymmetrizer_tabloid_mem t) a

/-- Acting on `{t}` gives the canonical intertwining map from the Young-symmetrizer ideal to
the polytabloid Specht module. -/
def spechtIdealToSubrepresentation (t : YoungTableau μ) :
    (spechtIdealRep t).ρ.IntertwiningMap (spechtSubrepresentation μ).toRepresentation where
  toLinearMap :=
    { toFun := fun x =>
        ⟨(permutationRep μ).asAlgebraHom
            (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
            (MonoidAlgebra.single (tabloid t) 1), spechtIdeal_apply_tabloid_mem t x⟩
      map_add' := fun x y => by
        apply Subtype.ext
        simp
      map_smul' := fun r x => by
        apply Subtype.ext
        simp }
  isIntertwining' g := by
    apply LinearMap.ext
    intro x
    apply Subtype.ext
    simp only [LinearMap.comp_apply]
    -- Unpack the two restricted actions so that the group-algebra multiplication law applies.
    change
      (permutationRep μ).asAlgebraHom
          (((spechtIdealRep t).ρ g x : spechtIdeal t) :
            MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
          (MonoidAlgebra.single (tabloid t) 1) =
        (permutationRep μ) g
          ((permutationRep μ).asAlgebraHom
            (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
            (MonoidAlgebra.single (tabloid t) 1))
    rw [spechtIdealRep_ρ_apply_coe, map_mul,
      Representation.asAlgebraHom_single_one, Module.End.mul_apply]

/-- The canonical comparison map is evaluation of an ideal element on the tabloid `{t}`. -/
@[simp]
theorem coe_spechtIdealToSubrepresentation_apply (t : YoungTableau μ) (x : spechtIdeal t) :
    ((spechtIdealToSubrepresentation t x : (spechtSubrepresentation μ).toSubmodule) :
        (permutationModule (shapePartition μ)).V) =
      (permutationModule (shapePartition μ)).ρ.asAlgebraHom
        (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
        (MonoidAlgebra.single (tabloid t) 1) :=
  (rfl)

/-- The coefficient of `{t}` in `c_t · {t}` is the order of the row group.  In particular the
canonical comparison map does not annihilate the generator of the Young-symmetrizer ideal. -/
@[simp]
theorem youngSymmetrizer_smul_tabloid_coeff_tabloid (t : YoungTableau μ) :
    ((permutationModule (shapePartition μ)).ρ.asAlgebraHom (youngSymmetrizer t)
        (MonoidAlgebra.single (tabloid t) 1)).coeff (tabloid t) =
      (Nat.card (rowSubgroup t) : ℚ) := by
  classical
  rw [youngSymmetrizer_def, map_mul, Module.End.mul_apply, ← polytabloid_def,
    rowSymmetrizer_def, map_sum, LinearMap.sum_apply, MonoidAlgebra.coeff_sum,
    Finsupp.finsetSum_apply]
  simp_rw [Representation.asAlgebraHom_of]
  have hfix (p : rowSubgroup t) :
      (p : Equiv.Perm (Fin μ.card))⁻¹ • tabloid t = tabloid t :=
    smul_tabloid_eq_self_iff.mpr (inv_mem p.property)
  have hterm (p : rowSubgroup t) :
      (Representation.ofMulAction ℚ (Equiv.Perm (Fin μ.card))
      (Equiv.Perm (Fin μ.card) ⧸ youngSubgroup (shapePartition μ))
      (p : Equiv.Perm (Fin μ.card)) (polytabloid t)).coeff (tabloid t) = 1 := by
    rw [Representation.coeff_ofMulAction, hfix, polytabloid_coeff_tabloid]
  simp_rw [hterm]
  rw [Finset.sum_const, Finset.card_univ, Nat.card_eq_fintype_card, nsmul_eq_mul, mul_one]

/-- The canonical comparison map from the Young-symmetrizer ideal to the polytabloid Specht
module is nonzero. -/
theorem spechtIdealToSubrepresentation_ne_zero (t : YoungTableau μ) :
    spechtIdealToSubrepresentation t ≠ 0 := by
  intro hzero
  have happ := DFunLike.congr_fun hzero
    (⟨youngSymmetrizer t, youngSymmetrizer_mem_spechtIdeal t⟩ : spechtIdeal t)
  have hval :
      (permutationRep μ).asAlgebraHom (youngSymmetrizer t)
          (MonoidAlgebra.single (tabloid t) 1) = 0 := by
    have hmap := coe_spechtIdealToSubrepresentation_apply t
      (⟨youngSymmetrizer t, youngSymmetrizer_mem_spechtIdeal t⟩ : spechtIdeal t)
    have happ' :
        spechtIdealToSubrepresentation t
            (⟨youngSymmetrizer t, youngSymmetrizer_mem_spechtIdeal t⟩ : spechtIdeal t) = 0 := by
      simpa using happ
    have hz :
        ↑(spechtIdealToSubrepresentation t
          (⟨youngSymmetrizer t, youngSymmetrizer_mem_spechtIdeal t⟩ : spechtIdeal t)) =
            (0 : (permutationModule (shapePartition μ)).V) := by
      simpa only [Submodule.coe_zero] using congrArg Subtype.val happ'
    exact hmap.symm.trans hz
  have hcoeff := congrArg
    (fun x : (permutationModule (shapePartition μ)).V => x.coeff (tabloid t)) hval
  rw [youngSymmetrizer_smul_tabloid_coeff_tabloid, MonoidAlgebra.coeff_zero] at hcoeff
  exact (Nat.cast_ne_zero.mpr
    (Nat.card_ne_zero.mpr ⟨inferInstance, inferInstance⟩ : Nat.card (rowSubgroup t) ≠ 0)) hcoeff

/-- **The Young-symmetrizer ideal and the polytabloid Specht module are equivalent
representations.** -/
def spechtIdealEquivSpechtSubrepresentation (t : YoungTableau μ) :
    (spechtIdealRep t).ρ.Equiv (spechtSubrepresentation μ).toRepresentation := by
  letI : (spechtSubrepresentation μ).toRepresentation.IsIrreducible :=
    isIrreducible_spechtSubrepresentation μ
  exact (spechtIdealToSubrepresentation t).ofBijective
    ((Representation.IsIrreducible.bijective_or_eq_zero
      (spechtIdealToSubrepresentation t)).resolve_right
        (spechtIdealToSubrepresentation_ne_zero t))

/-- The representation equivalence sends an ideal element to its action on the tabloid `{t}`. -/
@[simp]
theorem coe_spechtIdealEquivSpechtSubrepresentation_apply (t : YoungTableau μ)
    (x : spechtIdeal t) :
    (((spechtIdealEquivSpechtSubrepresentation t x :
        (spechtSubrepresentation μ).toSubmodule) :
        (permutationModule (shapePartition μ)).V)) =
      (permutationModule (shapePartition μ)).ρ.asAlgebraHom
        (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
        (MonoidAlgebra.single (tabloid t) 1) := by
  exact coe_spechtIdealToSubrepresentation_apply t x

/-- The Young-symmetrizer ideal and the polytabloid Specht module are isomorphic as objects of
`Rep ℚ (Equiv.Perm (Fin μ.card))`. -/
def spechtIdealIsoSpechtSubrepresentation (t : YoungTableau μ) :
    spechtIdealRep t ≅ Rep.of (spechtSubrepresentation μ).toRepresentation :=
  Rep.mkIso (spechtIdealEquivSpechtSubrepresentation t)

/-- The categorical comparison isomorphism sends an ideal element to its action on the tabloid
`{t}`. -/
@[simp]
theorem spechtIdealIsoSpechtSubrepresentation_hom_hom_apply_coe (t : YoungTableau μ)
    (x : spechtIdeal t) :
    (((spechtIdealIsoSpechtSubrepresentation t).hom.hom x :
        (spechtSubrepresentation μ).toSubmodule) :
        (permutationModule (shapePartition μ)).V) =
      (permutationModule (shapePartition μ)).ρ.asAlgebraHom
        (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
        (MonoidAlgebra.single (tabloid t) 1) := by
  rw [spechtIdealIsoSpechtSubrepresentation, Rep.mkIso_hom_hom_apply,
    Representation.Equiv.coe_toLinearMap,
    coe_spechtIdealEquivSpechtSubrepresentation_apply]

/-- The two presentations of the Specht module have the same dimension. -/
@[simp]
theorem finrank_spechtIdeal_eq_spechtSubrepresentation (t : YoungTableau μ) :
    Module.finrank ℚ (spechtIdeal t) =
      Module.finrank ℚ (spechtSubrepresentation μ).toSubmodule :=
  (spechtIdealEquivSpechtSubrepresentation t).toLinearEquiv.finrank_eq

/-- The two presentations of the Specht module have the same character. -/
@[simp]
theorem character_spechtIdeal_eq_spechtSubrepresentation (t : YoungTableau μ) :
    (spechtIdealRep t).ρ.character =
      (spechtSubrepresentation μ).toRepresentation.character :=
  _root_.Representation.char_iso (spechtIdealEquivSpechtSubrepresentation t)

end

end YoungTableau

end TauCeti
