/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Adjoint.Derivation
public import TauCeti.Geometry.Lie.Exponential.Basic

/-!
# Naturality of the Lie-group exponential under conjugation

Conjugation transports the integral curve generated by a tangent vector to the integral curve
generated by its tangent adjoint image. Evaluating at time one gives the conjugation formula for
the Lie-group exponential.

This advances Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `TauCeti.Lie.conj_mulInvariantIntegralCurve`: conjugation transports canonical invariant
  integral curves.
* `TauCeti.Lie.conj_mulInvariantExp`: conjugation commutes with the tangent-space exponential.
* `TauCeti.Lie.conj_lieExp`: conjugation commutes with the derivation-valued Lie-group
  exponential.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The conjugation formulas".
-/

public section

noncomputable section

namespace TauCeti.Lie

open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G]

attribute [local instance] LieGroup.minSmoothnessThree

local instance lieGroupBoundarylessManifold : BoundarylessManifold I G where
  isInteriorPoint' g :=
    ContMDiffMul.isInteriorPoint (I := I) (n := ∞) (by simp) g

/-- Conjugation transports the canonical invariant integral curve generated by `X` to the one
generated by the tangent adjoint image of `X`. -/
theorem conj_mulInvariantIntegralCurve (g : G) (X : GroupLieAlgebra I G) (t : ℝ) :
    g * mulInvariantIntegralCurve (I := I) (G := G) X 1 t * g⁻¹ =
      mulInvariantIntegralCurve (tangentAd (I := I) g X) 1 t := by
  let Φ := conjDiffeomorph (I := I) (n := 1) g
  let γ := mulInvariantIntegralCurve (I := I) (G := G) X 1
  have hcurve : IsMIntegralCurve (Φ ∘ γ)
      (mulInvariantVectorField (tangentAd (I := I) g X)) := by
    intro s
    have hγ := isMIntegralCurve_mulInvariantIntegralCurve
      (I := I) (G := G) X 1 s
    have hΦ := Φ.contMDiff.mdifferentiable (by simp) (γ s) |>.hasMFDerivAt
    have hcomp := hΦ.comp s hγ
    have hmap :
        (mfderiv I I Φ (γ s)).comp
            ((1 : ℝ →L[ℝ] ℝ).smulRight (mulInvariantVectorField X (γ s))) =
          (1 : ℝ →L[ℝ] ℝ).smulRight
            (mulInvariantVectorField (tangentAd (I := I) g X) (Φ (γ s))) := by
      apply ContinuousLinearMap.ext
      intro r
      simp only [ContinuousLinearMap.comp_apply, ContinuousLinearMap.smulRight_apply,
        one_apply_eq_self]
      dsimp only [Φ, γ]
      rw [map_smul, mfderiv_conjugation_mulInvariantVectorField, tangentAd_apply]
    change HasMFDerivAt (modelWithCornersSelf ℝ ℝ) I (Φ ∘ γ) s
      ((1 : ℝ →L[ℝ] ℝ).smulRight
        (mulInvariantVectorField (tangentAd (I := I) g X) (Φ (γ s))))
    rw [← hmap]
    exact hcomp
  have hzero : (Φ ∘ γ) 0 = (1 : G) := by simp [Φ, γ]
  have heq : Φ ∘ γ =
      mulInvariantIntegralCurve (tangentAd (I := I) g X) 1 :=
    eq_mulInvariantIntegralCurve (tangentAd (I := I) g X) 1 hzero hcurve
  simpa only [Φ, γ, Function.comp_apply, conjDiffeomorph_apply] using congrFun heq t

/-- Conjugation commutes with the tangent-space Lie-group exponential. -/
theorem conj_mulInvariantExp (g : G) (X : GroupLieAlgebra I G) :
    g * mulInvariantExp (I := I) (G := G) X * g⁻¹ =
      mulInvariantExp (tangentAd (I := I) g X) := by
  rw [mulInvariantExp_eq_mulInvariantIntegralCurve,
    mulInvariantExp_eq_mulInvariantIntegralCurve]
  exact conj_mulInvariantIntegralCurve g X 1

/-- Conjugation commutes with the derivation-valued Lie-group exponential. -/
theorem conj_lieExp (g : G) (X : LeftInvariantDerivation I G) :
    g * lieExp (I := I) X * g⁻¹ = lieExp (Ad (I := I) g X) := by
  rw [lieExp_eq_mulInvariantExp, lieExp_eq_mulInvariantExp]
  rw [conj_mulInvariantExp]
  congr 1
  rw [Ad_apply]
  rw [← leftInvariantDerivationLieEquivGroupLieAlgebra_apply,
    ← leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
  exact (leftInvariantDerivationLieEquivGroupLieAlgebra
    (I := I) (G := G)
    (ContMDiffMul.isInteriorPoint (I := I) (n := ∞) (by simp) (1 : G))).apply_symm_apply _ |>.symm

end TauCeti.Lie
