/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Adjoint.RepresentationDifferential
public import Mathlib.Analysis.ODE.ExistUnique
public import Mathlib.Analysis.SpecialFunctions.Exponential

/-!
# The adjoint action on the Lie-group exponential

The tangent adjoint representation along the one-parameter subgroup generated by `X` and the
operator exponential of `ad X` solve the same linear differential equation with the same initial
value. Uniqueness identifies them. Transport across the canonical continuous Lie equivalence then
proves the headline Layer 1 formula `Ad (lieExp X) = exp (ad X)`.

This advances Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main definitions

* `TauCeti.Lie.tangentAdContinuousLinearMap`: the continuous tangent endomorphism `ad X`.

## Main results

* `TauCeti.Lie.tangentAd_mulInvariantExp_apply`: the tangent adjoint-exponential formula.
* `TauCeti.Lie.tangentAdContinuousLinearMap_smul`: the tangent adjoint generator is linear in its
  Lie-algebra argument.
* `TauCeti.Lie.Ad_lieExp_apply`: the derivation adjoint-exponential formula evaluated on a vector.
* `TauCeti.Lie.Ad_lieExp`: the derivation adjoint-exponential formula as an operator identity.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The conjugation formulas".
-/

public section

noncomputable section

namespace TauCeti.Lie

open Set
open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G]

attribute [local instance] LieGroup.minSmoothnessThree

local instance lieGroupBoundarylessManifoldExponentialFormula : BoundarylessManifold I G where
  isInteriorPoint' g :=
    ContMDiffMul.isInteriorPoint (I := I) (n := ∞) (by simp) g

/-- The continuous endomorphism underlying `ad X` on the tangent Lie algebra. -/
def tangentAdContinuousLinearMap (X : GroupLieAlgebra I G) : E →L[ℝ] E :=
  LinearMap.toContinuousLinearMap (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X)

omit [T2Space G] in
@[simp]
theorem tangentAdContinuousLinearMap_apply (X Y : GroupLieAlgebra I G) :
    tangentAdContinuousLinearMap (I := I) X (@id E Y) =
      @id E (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X Y) := by
  rfl

omit [T2Space G] in
/-- The tangent adjoint generator depends linearly on its Lie-algebra argument. -/
theorem tangentAdContinuousLinearMap_smul (r : ℝ) (X : GroupLieAlgebra I G) :
    tangentAdContinuousLinearMap (I := I) (r • X) =
      r • tangentAdContinuousLinearMap (I := I) X := by
  apply ContinuousLinearMap.ext
  intro Y
  change @id E (LieAlgebra.ad ℝ (GroupLieAlgebra I G) (r • X)
      (@id (GroupLieAlgebra I G) Y)) =
    r • @id E (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X
      (@id (GroupLieAlgebra I G) Y))
  rw [map_smul]
  rfl

/-- At every time, the tangent adjoint orbit solves the linear ODE generated by `ad X`. -/
theorem hasDerivAt_tangentAd_mulInvariantExp_smul_apply_at
    (X Y : GroupLieAlgebra I G) (t : ℝ) :
    let f : ℝ → E := fun s => @id E (tangentAd (I := I)
      (mulInvariantExp (I := I) (G := G) (s • X)) Y)
    HasDerivAt f (tangentAdContinuousLinearMap (I := I) X (f t)) t := by
  dsimp only
  let f : ℝ → E := fun s => @id E (tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (s • X)) Y)
  have hzero := hasDerivAt_tangentAd_mulInvariantExp_smul_apply
    (I := I) (G := G) X (@id (GroupLieAlgebra I G) (f t))
  have hshift : f = fun s => @id E (tangentAd (I := I)
      (mulInvariantExp (I := I) (G := G) ((s - t) • X))
      (@id (GroupLieAlgebra I G) (f t))) := by
    funext s
    change @id E (tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) (s • X)) Y) =
      @id E (tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (tangentAd (I := I) (mulInvariantExp (I := I) (G := G) (t • X)) Y))
    calc
      _ = @id E (tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) (((s - t) + t) • X)) Y) := by
        rw [sub_add_cancel]
      _ = @id E (tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) ((s - t) • X) *
            mulInvariantExp (I := I) (G := G) (t • X)) Y) := by
        rw [mulInvariantExp_add_smul]
      _ = _ := by rw [tangentAd_mul]; rfl
  have hcomp := hzero.scomp_of_eq t ((hasDerivAt_id t).sub_const t) (by simp)
  have hderiv : HasDerivAt
      (fun s => @id E (tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (@id (GroupLieAlgebra I G) (f t))))
      (@id E (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X
        (@id (GroupLieAlgebra I G) (f t)))) t := by
    change HasDerivAt
      (fun s => @id E (tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) ((s - t) • X))
        (@id (GroupLieAlgebra I G) (f t)))) _ t at hcomp
    simpa only [one_smul] using hcomp
  rw [← hshift] at hderiv
  change HasDerivAt f (tangentAdContinuousLinearMap (I := I) X (f t)) t
  apply hderiv.congr_deriv
  rfl

omit [T2Space G] in
/-- Applying the tangent operator exponential to `Y` solves the linear ODE generated by `ad X`. -/
theorem hasDerivAt_exp_tangentAdContinuousLinearMap_apply
    (X Y : GroupLieAlgebra I G) (t : ℝ) :
    let A := tangentAdContinuousLinearMap (I := I) X
    HasDerivAt (fun s : ℝ => NormedSpace.exp (s • A) (@id E Y))
      (A (NormedSpace.exp (t • A) (@id E Y))) t := by
  dsimp only
  let A := tangentAdContinuousLinearMap (I := I) X
  have hexp := hasDerivAt_exp_smul_const' A t
  have heval := (ContinuousLinearMap.apply ℝ E (@id E Y)).hasFDerivAt
    |>.comp_hasDerivAt t hexp
  convert heval using 1 <;> rfl

/-- The tangent adjoint action of `mulInvariantExp X`, evaluated on `Y`, is the operator
exponential of `ad X`. -/
theorem tangentAd_mulInvariantExp_apply (X Y : GroupLieAlgebra I G) :
    @id E (tangentAd (I := I) (mulInvariantExp (I := I) (G := G) X) Y) =
      NormedSpace.exp (tangentAdContinuousLinearMap (I := I) X) (@id E Y) := by
  let A := tangentAdContinuousLinearMap (I := I) X
  let f : ℝ → E := fun t => @id E (tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (t • X)) Y)
  let g : ℝ → E := fun t => NormedSpace.exp (t • A) (@id E Y)
  have hf (t : ℝ) : HasDerivAt f (A (f t)) t := by
    simpa only [f, A] using
      hasDerivAt_tangentAd_mulInvariantExp_smul_apply_at (I := I) (G := G) X Y t
  have hg (t : ℝ) : HasDerivAt g (A (g t)) t := by
    simpa only [g, A] using
      hasDerivAt_exp_tangentAdContinuousLinearMap_apply (I := I) (G := G) X Y t
  have hv : ∀ _ : ℝ, LipschitzOnWith ‖A‖₊ A univ :=
    fun _ => A.lipschitz.lipschitzOnWith
  have hinitial : f 0 = g 0 := by
    dsimp only [f, g]
    rw [zero_smul, mulInvariantExp_zero, tangentAd_one, LieEquiv.refl_apply]
    rw [zero_smul, NormedSpace.exp_zero, one_apply_eq_self]
  have hfg : f = g := ODE_solution_unique_univ (K := ‖A‖₊)
    (v := fun _ => A) (s := fun _ => univ) (t₀ := 0) hv
    (fun t => ⟨hf t, mem_univ _⟩) (fun t => ⟨hg t, mem_univ _⟩) hinitial
  simpa only [f, g, one_smul, A] using congrFun hfg 1

/-- The adjoint action of the one-parameter subgroup generated by `X` fixes `X`. -/
theorem tangentAd_mulInvariantExp_smul_self (X : GroupLieAlgebra I G) (t : ℝ) :
    tangentAd (I := I) (mulInvariantExp (I := I) (G := G) (t • X)) X = X := by
  let A := tangentAdContinuousLinearMap (I := I) X
  let f : ℝ → E := fun s => @id E (tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (s • X)) X)
  let g : ℝ → E := fun _ => @id E X
  have hf (s : ℝ) : HasDerivAt f (A (f s)) s := by
    simpa only [f, A] using
      hasDerivAt_tangentAd_mulInvariantExp_smul_apply_at (I := I) (G := G) X X s
  have hAX : A (@id E X) = 0 := by
    change @id E (LieAlgebra.ad ℝ (GroupLieAlgebra I G) X X) = 0
    simp only [LieAlgebra.ad_apply, lie_self]
    rfl
  have hg (s : ℝ) : HasDerivAt g (A (g s)) s := by
    rw [show A (g s) = 0 by simpa only [g] using hAX]
    exact hasDerivAt_const s (@id E X)
  have hv : ∀ _ : ℝ, LipschitzOnWith ‖A‖₊ A univ :=
    fun _ => A.lipschitz.lipschitzOnWith
  have hinitial : f 0 = g 0 := by
    dsimp only [f, g]
    rw [zero_smul, mulInvariantExp_zero, tangentAd_one, LieEquiv.refl_apply]
  have hfg : f = g := ODE_solution_unique_univ (K := ‖A‖₊)
    (v := fun _ => A) (s := fun _ => univ) (t₀ := 0) hv
    (fun s => ⟨hf s, mem_univ _⟩) (fun s => ⟨hg s, mem_univ _⟩) hinitial
  change @id E (tangentAd (I := I)
    (mulInvariantExp (I := I) (G := G) (t • X)) X) = @id E X
  exact congrFun hfg t

/-- Conjugating the continuous derivation adjoint by the canonical model-space equivalence gives
the continuous tangent adjoint. -/
theorem conjContinuousAlgEquiv_adContinuousLinearMap
    (X : LeftInvariantDerivation I G) :
    let eIso := leftInvariantDerivationLinearIsometryEquivModelVectorSpace
      (I := I) (G := G)
    let eLie := leftInvariantDerivationLieEquivGroupLieAlgebra
      (I := I) (G := G) BoundarylessManifold.isInteriorPoint
    eIso.toContinuousLinearEquiv.conjContinuousAlgEquiv
        (adContinuousLinearMap (I := I) X) =
      tangentAdContinuousLinearMap (I := I) (eLie X) := by
  dsimp only
  let eLie := leftInvariantDerivationLieEquivGroupLieAlgebra
    (I := I) (G := G) BoundarylessManifold.isInteriorPoint
  let eIso := leftInvariantDerivationLinearIsometryEquivModelVectorSpace
    (I := I) (G := G)
  have eIso_apply (Z : LeftInvariantDerivation I G) :
      eIso Z = @id E (eLie Z) := by
    simp only [eLie, eIso,
      leftInvariantDerivationLinearIsometryEquivModelVectorSpace_apply,
      leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
    rfl
  apply ContinuousLinearMap.ext
  intro Z
  simp only [ContinuousLinearEquiv.conjContinuousAlgEquiv_apply_apply,
    LinearIsometryEquiv.coe_toContinuousLinearEquiv]
  let W := eIso.symm Z
  have hW : eIso W = Z := eIso.apply_symm_apply Z
  change eIso (adContinuousLinearMap (I := I) X W) =
    tangentAdContinuousLinearMap (I := I) (eLie X) Z
  rw [← hW, adContinuousLinearMap_apply, eIso_apply W,
    tangentAdContinuousLinearMap_apply, eIso_apply, LieAlgebra.ad_apply,
    LieAlgebra.ad_apply, ← eLie.map_lie]

/-- The adjoint action of `lieExp X`, evaluated on `Y`, is the operator exponential of `ad X`. -/
theorem Ad_lieExp_apply (X Y : LeftInvariantDerivation I G) :
    let _ : FiniteDimensional ℝ (LeftInvariantDerivation I G) :=
      finiteDimensional_leftInvariantDerivation
        (I := I) (G := G) BoundarylessManifold.isInteriorPoint
    Ad (I := I) (lieExp X) Y =
      NormedSpace.exp (adContinuousLinearMap (I := I) X) Y := by
  dsimp only
  let _ : FiniteDimensional ℝ (LeftInvariantDerivation I G) :=
    finiteDimensional_leftInvariantDerivation
      (I := I) (G := G) BoundarylessManifold.isInteriorPoint
  let eLie := leftInvariantDerivationLieEquivGroupLieAlgebra
    (I := I) (G := G) BoundarylessManifold.isInteriorPoint
  let eIso := leftInvariantDerivationLinearIsometryEquivModelVectorSpace
    (I := I) (G := G)
  let _ : CompleteSpace (LeftInvariantDerivation I G) :=
    FiniteDimensional.complete ℝ (LeftInvariantDerivation I G)
  let _ : NormedAlgebra ℚ
      (LeftInvariantDerivation I G →L[ℝ] LeftInvariantDerivation I G) :=
    NormedAlgebra.restrictScalars ℚ ℝ _
  let _ : NormedAlgebra ℚ (E →L[ℝ] E) :=
    NormedAlgebra.restrictScalars ℚ ℝ _
  let c := eIso.toContinuousLinearEquiv.conjContinuousAlgEquiv
  have eIso_apply (Z : LeftInvariantDerivation I G) :
      eIso Z = @id E (eLie Z) := by
    simp only [eLie, eIso,
      leftInvariantDerivationLinearIsometryEquivModelVectorSpace_apply,
      leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
    rfl
  have hc : c (adContinuousLinearMap (I := I) X) =
      tangentAdContinuousLinearMap (I := I) (eLie X) := by
    exact conjContinuousAlgEquiv_adContinuousLinearMap (I := I) (G := G) X
  have hexp : c (NormedSpace.exp (adContinuousLinearMap (I := I) X)) =
      NormedSpace.exp (tangentAdContinuousLinearMap (I := I) (eLie X)) := by
    have hmap := NormedSpace.map_exp c.toAlgHom c.continuous
      (adContinuousLinearMap (I := I) X)
    have hmap' : c (NormedSpace.exp (adContinuousLinearMap (I := I) X)) =
        NormedSpace.exp (c (adContinuousLinearMap (I := I) X)) := by
      calc
        c (NormedSpace.exp (adContinuousLinearMap (I := I) X)) =
            c.toAlgEquiv (NormedSpace.exp (adContinuousLinearMap (I := I) X)) :=
          (congrFun (ContinuousAlgEquiv.coe_toAlgEquiv c) _).symm
        _ = NormedSpace.exp (c.toAlgEquiv (adContinuousLinearMap (I := I) X)) := hmap
        _ = NormedSpace.exp (c (adContinuousLinearMap (I := I) X)) := by
          rw [congrFun (ContinuousAlgEquiv.coe_toAlgEquiv c)
            (adContinuousLinearMap (I := I) X)]
    rw [hc] at hmap'
    exact hmap'
  have hexpY := congrArg (fun L : E →L[ℝ] E => L (eIso Y)) hexp
  have htangent := tangentAd_mulInvariantExp_apply
    (I := I) (G := G) (eLie X) (eLie Y)
  have eLie_apply (Z : LeftInvariantDerivation I G) :
      leftInvariantDerivationEquivGroupLieAlgebra
          (I := I) (G := G) BoundarylessManifold.isInteriorPoint Z = eLie Z := by
    rw [← leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
  have hleft : eIso (Ad (I := I) (lieExp X) Y) =
      @id E (tangentAd (I := I)
        (mulInvariantExp (I := I) (G := G) (eLie X)) (eLie Y)) := by
    rw [Ad_apply, lieExp_eq_mulInvariantExp,
      leftInvariantDerivationLieEquivGroupLieAlgebra_apply]
    rw [eLie_apply]
    rw [eIso_apply, eLie.apply_symm_apply]
  have hright : eIso
      (NormedSpace.exp (adContinuousLinearMap (I := I) X) Y) =
      NormedSpace.exp (tangentAdContinuousLinearMap (I := I) (eLie X))
        (@id E (eLie Y)) := by
    rw [← eIso_apply Y]
    have hinv : eIso.toContinuousLinearEquiv.symm (eIso Y) = Y :=
      eIso.toContinuousLinearEquiv.symm_apply_apply Y
    simpa only [c, ContinuousLinearEquiv.conjContinuousAlgEquiv_apply_apply,
      LinearIsometryEquiv.coe_toContinuousLinearEquiv,
      hinv] using hexpY
  apply eIso.injective
  exact hleft.trans (htangent.trans hright.symm)

/-- The adjoint action of `lieExp X` is the operator exponential of `ad X`. -/
theorem Ad_lieExp (X : LeftInvariantDerivation I G) :
    let _ : FiniteDimensional ℝ (LeftInvariantDerivation I G) :=
      finiteDimensional_leftInvariantDerivation
        (I := I) (G := G) BoundarylessManifold.isInteriorPoint
    LinearMap.toContinuousLinearMap (Ad (I := I) (lieExp X)).toLinearEquiv.toLinearMap =
      NormedSpace.exp (adContinuousLinearMap (I := I) X) := by
  dsimp only
  apply ContinuousLinearMap.ext
  exact Ad_lieExp_apply (I := I) (G := G) X

end TauCeti.Lie

