/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.InvariantVectorField

/-!
# Right-invariant vector fields on Lie groups

Mathlib's `mulInvariantVectorField` is the left-invariant field generated by a tangent vector at
the identity. This file supplies its right-invariant counterpart and the regularity needed to
compare the two fields in the infinitesimal adjoint calculation.

This supplies a prerequisite for Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main definitions

* `mulRightInvariantVectorField`: the right-invariant field generated at the identity.

## Main results

* `mulRightInvariantVectorField_one`: the field has the prescribed value at the identity.
* `contMDiff_mulRightInvariantVectorField_infty`: a right-invariant field is smooth.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The infinitesimal adjoint".
-/

public section

noncomputable section

open Bundle Manifold
open scoped ContDiff Manifold

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

/-- The right-invariant vector field generated by a tangent vector at the identity. -/
def mulRightInvariantVectorField (v : GroupLieAlgebra I G) (g : G) : TangentSpace I g :=
  mfderiv I I (fun x : G => x * g) 1 v

/-- At the identity, the right-invariant vector field generated by `v` equals `v`. -/
@[simp]
theorem mulRightInvariantVectorField_one (v : GroupLieAlgebra I G) :
    mulRightInvariantVectorField v (1 : G) = v := by
  rw [mulRightInvariantVectorField]
  rw [show (fun x : G => x * 1) = id by funext x; simp, mfderiv_id]
  rfl

/-- The right-invariant vector field is the derivative of right multiplication. -/
theorem mulRightInvariantVectorField_apply (v : GroupLieAlgebra I G) (g : G) :
    mulRightInvariantVectorField v g = mfderiv I I (fun x : G => x * g) 1 v :=
  (rfl)

/-- In model coordinates, the right-invariant vector field is jointly `C^n` in its generating
tangent vector and group point when multiplication is `C^(n + 1)`. -/
theorem contMDiff_mulRightInvariantVectorField_modelSpace {n : ℕ∞ω}
    [ContMDiffMul I (n + 1) G] :
    let _ : IsManifold I 1 G := IsManifold.of_le (n := n + 1) le_add_self
    ContMDiff (𝓘(𝕜, E).prod I) I.tangent n
      (fun p : E × G =>
        (mulRightInvariantVectorField (I := I) (G := G) p.1 p.2 : TangentBundle I G)) := by
  let _ : IsManifold I 1 G := IsManifold.of_le (n := n + 1) le_add_self
  let fg : E × G → TangentBundle I G := fun p => TotalSpace.mk' E p.2 0
  have sfg : ContMDiff (𝓘(𝕜, E).prod I) I.tangent n fg :=
    (contMDiff_zeroSection 𝕜 (TangentSpace I : G → Type _)).comp contMDiff_snd
  let fv : E × G → TangentBundle I G := fun p => TotalSpace.mk' E 1 p.1
  have sfv : ContMDiff (𝓘(𝕜, E).prod I) I.tangent n fv := by
    intro p
    rw [Bundle.contMDiffAt_totalSpace]
    constructor
    · simpa only [fv] using
        (contMDiffAt_const : ContMDiffAt (𝓘(𝕜, E).prod I) I n
          (fun _ : E × G => (1 : G)) p)
    · have hone : (1 : G) ∈ (extChartAt I (1 : G)).source := mem_extChartAt_source _
      have hfun :
          (fun q : E × G =>
            (trivializationAt E (TangentSpace I) ((fv p).proj) (fv q)).2) = fun q => q.1 := by
        funext q
        rw [TangentBundle.trivializationAt_apply]
        change tangentCoordChange I (1 : G) (1 : G) (1 : G) q.1 = q.1
        rw [tangentCoordChange_self hone]
      rw [hfun]
      exact contMDiffAt_fst
  let F₁ : E × G → TangentBundle I G × TangentBundle I G := fun p => (fv p, fg p)
  have S₁ : ContMDiff (𝓘(𝕜, E).prod I) (I.tangent.prod I.tangent) n F₁ :=
    sfv.prodMk sfg
  let F₂ : TangentBundle I G × TangentBundle I G → TangentBundle (I.prod I) (G × G) :=
    (equivTangentBundleProd I G I G).symm
  have S₂ : ContMDiff (I.tangent.prod I.tangent) (I.prod I).tangent n F₂ :=
    contMDiff_equivTangentBundleProd_symm
  let F₃ : TangentBundle (I.prod I) (G × G) → TangentBundle I G :=
    tangentMap% (fun p : G × G => p.1 * p.2)
  have S₃ : ContMDiff (I.prod I).tangent I.tangent n F₃ :=
    (contMDiff_mul I (n + 1)).contMDiff_tangentMap le_rfl
  let S := (S₃.comp S₂).comp S₁
  convert! S with p
  · simp [F₁, F₂, F₃, fg, fv]
  · simp only [Function.comp_apply, tangentMap, F₃, F₂, F₁, fg, fv]
    rw [mfderiv_prod_eq_add_apply
      ((contMDiff_mul I (n + 1)).mdifferentiableAt (by simp))]
    simp +instances [mulRightInvariantVectorField, equivTangentBundleProd]
    rfl

/-- A right-invariant vector field on a smooth Lie group is smooth. -/
theorem contMDiff_mulRightInvariantVectorField_infty
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G) :
    ContMDiff I I.tangent ∞
      (fun g : G => (mulRightInvariantVectorField v g : TangentBundle I G)) := by
  let _ : ContMDiffMul I (∞ + 1) G := by
    simpa using (inferInstance : ContMDiffMul I ∞ G)
  have h := contMDiff_mulRightInvariantVectorField_modelSpace (I := I) (G := G) (n := ∞)
  exact h.comp (contMDiff_const.prodMk contMDiff_id)

/-- Differentiating a smooth scalar function along a right-invariant vector field gives a smooth
scalar function. -/
theorem contMDiff_mvfderiv_mulRightInvariantVectorField
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G)
    (f : C^∞⟮I, G; 𝕜⟯) :
    ContMDiff I (modelWithCornersSelf 𝕜 𝕜) ∞
      (fun g => mvfderiv I f g (mulRightInvariantVectorField v g)) := by
  let df : TangentBundle I G → TangentBundle (modelWithCornersSelf 𝕜 𝕜) 𝕜 :=
    tangentMap% (f : G → 𝕜)
  have hdf : ContMDiff I.tangent (modelWithCornersSelf 𝕜 𝕜).tangent ∞ df :=
    f.contMDiff.contMDiff_tangentMap (by simp)
  have hsnd : ContMDiff (modelWithCornersSelf 𝕜 𝕜).tangent
      (modelWithCornersSelf 𝕜 𝕜) ∞
      (fun p : TangentBundle (modelWithCornersSelf 𝕜 𝕜) 𝕜 => p.2) :=
    contMDiff_snd_tangentBundle_modelSpace 𝕜 (modelWithCornersSelf 𝕜 𝕜)
  change ContMDiff I (modelWithCornersSelf 𝕜 𝕜) ∞
    (fun g => mfderiv I (modelWithCornersSelf 𝕜 𝕜) f g
      (mulRightInvariantVectorField v g))
  have h := hsnd.comp (hdf.comp (contMDiff_mulRightInvariantVectorField_infty v))
  exact h.congr fun g => rfl
