/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Adjoint.ExponentialFormula
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus

/-!
# First variations of exponential lines

This file packages two differential facts used to compute the derivative of the Lie-group
exponential. An exponential line solves its invariant differential equation at every time, and
two invariant directions introduced by consecutive exponential factors add at their common
basepoint.

This advances Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `TauCeti.Lie.hasMFDerivAt_mulInvariantExp_smul_at`: the velocity of an exponential line at an
  arbitrary time.
* `TauCeti.Lie.ContMDiffMap.hasDerivAt_comp_mul_mulInvariantExp_pair`: the velocity of two
  consecutive exponential perturbations.
* `TauCeti.Lie.ContMDiffMap.hasDerivAt_exponentialVariation`: the first variation of a product of
  exponential lines.
* `TauCeti.Lie.ContMDiffMap.deriv_timeFDeriv_exponentialVariation`: the variation's time derivative
  is the adjoint orbit of its initial velocity.
* `TauCeti.Lie.ContMDiffMap.timeFDeriv_exponentialVariation_one`: the endpoint variation is the
  integral of that adjoint orbit.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The conjugation formulas".
-/

public section

noncomputable section

namespace TauCeti.Lie

open Manifold
open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G]

local instance lieGroupBoundarylessManifoldExponentialVariation : BoundarylessManifold I G where
  isInteriorPoint' g :=
    ContMDiffMul.isInteriorPoint (I := I) (n := ∞) (by simp) g

attribute [local instance] LieGroup.minSmoothnessThree

/-- At every time, an exponential line has the left-invariant velocity generated by its defining
tangent vector. -/
theorem hasMFDerivAt_mulInvariantExp_smul_at (X : GroupLieAlgebra I G) (t : ℝ) :
    HasMFDerivAt 𝓘(ℝ, ℝ) I
      (fun s : ℝ => mulInvariantExp (I := I) (G := G) (s • X)) t
      ((1 : ℝ →L[ℝ] ℝ).smulRight
        (mulInvariantVectorField X
          (mulInvariantExp (I := I) (G := G) (t • X)))) := by
  have hcurve := isMIntegralCurve_mulInvariantIntegralCurve
    (I := I) (G := G) X (1 : G) t
  have hfun : (fun s : ℝ => mulInvariantExp (I := I) (G := G) (s • X)) =
      mulInvariantIntegralCurve (I := I) (G := G) X 1 := by
    funext s
    rw [mulInvariantExp_smul]
  rw [hfun]
  rw [congrFun hfun t]
  exact hcurve

private theorem exponentialVariation_shift (X Z : GroupLieAlgebra I G) (s r : ℝ) :
    mulInvariantExp (I := I) (G := G) ((-r) • X) *
        mulInvariantExp (I := I) (G := G) (r • Z) =
      (mulInvariantExp (I := I) (G := G) ((-s) • X) *
          mulInvariantExp (I := I) (G := G) (s • Z)) *
        mulInvariantExp (I := I) (G := G)
          ((r - s) • tangentAd (I := I)
            (mulInvariantExp (I := I) (G := G) (s • Z))⁻¹ (-X)) *
        mulInvariantExp (I := I) (G := G) ((r - s) • Z) := by
  let B := mulInvariantExp (I := I) (G := G) (s • Z)
  have hconj := conj_mulInvariantExp (I := I) (G := G) B⁻¹ ((s - r) • X)
  have hAd : tangentAd (I := I) B⁻¹ ((s - r) • X) =
      (r - s) • tangentAd (I := I) B⁻¹ (-X) := by
    rw [map_smul, map_neg]
    module
  rw [hAd] at hconj
  have hXsplit : mulInvariantExp (I := I) (G := G) ((-r) • X) =
      mulInvariantExp (I := I) (G := G) ((-s) • X) *
        mulInvariantExp (I := I) (G := G) ((s - r) • X) := by
    rw [← mulInvariantExp_add_smul]
    congr 2
    module
  have hZsplit : mulInvariantExp (I := I) (G := G) (r • Z) =
      B * mulInvariantExp (I := I) (G := G) ((r - s) • Z) := by
    rw [show B = mulInvariantExp (I := I) (G := G) (s • Z) by rfl]
    rw [← mulInvariantExp_add_smul]
    congr 2
    module
  rw [hXsplit, hZsplit]
  change _ * _ * (B * _) = (_ * B) * _ * _
  rw [← hconj]
  simp only [inv_inv]
  group

/-- Two consecutive exponential perturbations based at `g` have initial velocity generated by
the sum of their tangent vectors. -/
theorem ContMDiffMap.hasDerivAt_comp_mul_mulInvariantExp_pair
    (f : C^∞⟮I, G; ℝ⟯) (g : G) (X Y : GroupLieAlgebra I G) :
    HasDerivAt
      (fun t : ℝ => f (g * mulInvariantExp (I := I) (G := G) (t • X) *
        mulInvariantExp (I := I) (G := G) (t • Y)))
      (mvfderiv I f g (mulInvariantVectorField (X + Y) g)) 0 := by
  let F : ℝ × ℝ → ℝ := fun p =>
    f (g * mulInvariantExp (I := I) (G := G) (p.1 • X) *
      mulInvariantExp (I := I) (G := G) (p.2 • Y))
  have hX : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) X
  have hY : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • Y)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) Y
  have hMprod : ContMDiff (𝓘(ℝ, ℝ).prod 𝓘(ℝ, ℝ)) I ∞
      (fun p : ℝ × ℝ =>
        g * mulInvariantExp (I := I) (G := G) (p.1 • X) *
          mulInvariantExp (I := I) (G := G) (p.2 • Y)) :=
    (contMDiff_const.mul (hX.comp contMDiff_fst)).mul (hY.comp contMDiff_snd)
  have hM : ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞
      (fun p : ℝ × ℝ =>
        g * mulInvariantExp (I := I) (G := G) (p.1 • X) *
          mulInvariantExp (I := I) (G := G) (p.2 • Y)) := by
    rw [modelWithCornersSelf_prod, ← chartedSpaceSelf_prod]
    exact hMprod
  have hF : ContDiff ℝ ∞ F := (f.contMDiff.comp hM).contDiff
  have hdiag : HasDerivAt (fun t : ℝ => F (t, t))
      (fderiv ℝ F (0, 0) (1, 1)) 0 := by
    have hemb : HasDerivAt (fun t : ℝ => (t, t)) (1, 1) 0 :=
      (hasDerivAt_id (𝕜 := ℝ) 0).prodMk (hasDerivAt_id (𝕜 := ℝ) 0)
    exact (hF.differentiable (by simp) (0, 0)).hasFDerivAt.comp_hasDerivAt
      (f := fun t : ℝ => (t, t)) 0 hemb
  have hfAt := f.contMDiff.mdifferentiable (by simp) g |>.hasMFDerivAt
  have hleft := HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul hfAt X
  have hright := HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul hfAt Y
  have hXpartial : fderiv ℝ F (0, 0) (1, 0) =
      mvfderiv I f g (mulInvariantVectorField X g) := by
    have hemb : HasDerivAt (fun t : ℝ => (t, (0 : ℝ))) (1, 0) 0 :=
      (hasDerivAt_id (𝕜 := ℝ) 0).prodMk (hasDerivAt_const (x := 0) 0)
    have hpartial := (hF.differentiable (by simp) (0, 0)).hasFDerivAt
      |>.comp_hasDerivAt (f := fun t : ℝ => (t, (0 : ℝ))) 0 hemb
    have hleft' : HasDerivAt (fun t : ℝ => F (t, 0))
        (mvfderiv I f g (mulInvariantVectorField X g)) 0 := by
      convert hleft using 1
      · funext t
        simp only [F, zero_smul, mulInvariantExp_zero, mul_one]
      · with_unfolding_all rfl
    exact hpartial.unique hleft'
  have hYpartial : fderiv ℝ F (0, 0) (0, 1) =
      mvfderiv I f g (mulInvariantVectorField Y g) := by
    have hemb : HasDerivAt (fun t : ℝ => ((0 : ℝ), t)) (0, 1) 0 :=
      (hasDerivAt_const (x := 0) 0).prodMk (hasDerivAt_id (𝕜 := ℝ) 0)
    have hpartial := (hF.differentiable (by simp) (0, 0)).hasFDerivAt
      |>.comp_hasDerivAt (f := fun t : ℝ => ((0 : ℝ), t)) 0 hemb
    have hright' : HasDerivAt (fun t : ℝ => F (0, t))
        (mvfderiv I f g (mulInvariantVectorField Y g)) 0 := by
      convert hright using 1
      · funext t
        simp only [F, zero_smul, mulInvariantExp_zero, mul_one]
      · with_unfolding_all rfl
    exact hpartial.unique hright'
  apply hdiag.congr_deriv
  calc
    fderiv ℝ F (0, 0) (1, 1) =
        fderiv ℝ F (0, 0) (1, 0) + fderiv ℝ F (0, 0) (0, 1) := by
      calc
        fderiv ℝ F (0, 0) (1, 1) =
            fderiv ℝ F (0, 0) ((1, 0) + (0, 1)) := by norm_num
        _ = _ := map_add _ _ _
    _ = mvfderiv I f g (mulInvariantVectorField X g) +
        mvfderiv I f g (mulInvariantVectorField Y g) := by
      rw [hXpartial, hYpartial]
    _ = mvfderiv I f g (mulInvariantVectorField (X + Y) g) := by
      rw [mulInvariantVectorField_add]
      change _ + _ = mvfderiv I f g (_ + _)
      rw [map_add]

/-- The time derivative of the left-trivialized two-parameter exponential variation is generated
by the adjoint translate of the varied direction. -/
theorem ContMDiffMap.hasDerivAt_exponentialVariation
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) (s t : ℝ) :
    let Z := X + t • Y
    let B := mulInvariantExp (I := I) (G := G) (s • Z)
    let g := mulInvariantExp (I := I) (G := G) ((-s) • X) * B
    HasDerivAt
      (fun r : ℝ => f (mulInvariantExp (I := I) (G := G) ((-r) • X) *
        mulInvariantExp (I := I) (G := G) (r • Z)))
      (mvfderiv I f g
        (mulInvariantVectorField (t • tangentAd (I := I) B⁻¹ Y) g)) s := by
  dsimp only
  let Z : GroupLieAlgebra I G := X + t • Y
  let B : G := mulInvariantExp (I := I) (G := G) (s • Z)
  let g : G := mulInvariantExp (I := I) (G := G) ((-s) • X) * B
  let U : GroupLieAlgebra I G := tangentAd (I := I) B⁻¹ (-X)
  have hfixed : tangentAd (I := I) B⁻¹ Z = Z := by
    have h := tangentAd_mulInvariantExp_smul_self (I := I) (G := G) Z (-s)
    have hB : mulInvariantExp (I := I) (G := G) ((-s) • Z) = B⁻¹ := by
      rw [show (-s) • Z = -(s • Z) by module, mulInvariantExp_neg]
    rw [hB] at h
    exact h
  have hdirection : U + Z = t • tangentAd (I := I) B⁻¹ Y := by
    change tangentAd (I := I) B⁻¹ (-X) + Z = _
    rw [← hfixed, ← map_add, show -X + Z = t • Y by simp only [Z]; module,
      map_smul]
  have hbase := ContMDiffMap.hasDerivAt_comp_mul_mulInvariantExp_pair
    (I := I) (G := G) f g U Z
  have hshift := hbase.scomp_of_eq s ((hasDerivAt_id s).sub_const s) (by simp)
  have hshift' : HasDerivAt
      (((fun h : ℝ => f (g * mulInvariantExp (I := I) (G := G) (h • U) *
        mulInvariantExp (I := I) (G := G) (h • Z))) ∘ fun r => r - s))
      (mvfderiv I f g (mulInvariantVectorField (U + Z) g)) s := by
    simpa only [id_eq, one_smul] using hshift
  have hfun :
      ((fun h : ℝ => f (g * mulInvariantExp (I := I) (G := G) (h • U) *
        mulInvariantExp (I := I) (G := G) (h • Z))) ∘ fun r => r - s) =
      fun r : ℝ => f (mulInvariantExp (I := I) (G := G) ((-r) • X) *
        mulInvariantExp (I := I) (G := G) (r • Z)) := by
    funext r
    simp only [Function.comp_apply]
    apply congrArg f
    change (mulInvariantExp (I := I) (G := G) ((-s) • X) *
        mulInvariantExp (I := I) (G := G) (s • Z)) *
          mulInvariantExp (I := I) (G := G)
            ((r - s) • tangentAd (I := I)
              (mulInvariantExp (I := I) (G := G) (s • Z))⁻¹ (-X)) *
          mulInvariantExp (I := I) (G := G) ((r - s) • Z) = _
    exact (exponentialVariation_shift (I := I) (G := G) X Z s r).symm
  rw [hfun] at hshift'
  apply hshift'.congr_deriv
  rw [hdirection]

/-- A smooth scalar function evaluated on the left-trivialized exponential variation is jointly
smooth in the varied direction and time. -/
theorem ContMDiffMap.contDiff_exponentialVariation
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) :
    ContDiff ℝ ∞ (fun p : ℝ × ℝ =>
      f (mulInvariantExp (I := I) (G := G) ((-p.2) • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y)))) := by
  have hleftArg : ContMDiff 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, E) ∞
      (fun p : ℝ × ℝ => @id E ((-p.2) • X)) := by
    exact (show ContDiff ℝ ∞ (fun p : ℝ × ℝ => @id E ((-p.2) • X)) by
      fun_prop).contMDiff
  have hrightArg : ContMDiff 𝓘(ℝ, ℝ × ℝ) 𝓘(ℝ, E) ∞
      (fun p : ℝ × ℝ => @id E (p.2 • (X + p.1 • Y))) := by
    exact (show ContDiff ℝ ∞
      (fun p : ℝ × ℝ => @id E (p.2 • (X + p.1 • Y))) by fun_prop).contMDiff
  have hleft : ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞
      (fun p : ℝ × ℝ => mulInvariantExp (I := I) (G := G) ((-p.2) • X)) :=
    (contMDiff_mulInvariantExp (I := I) (G := G)).comp hleftArg
  have hright : ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞
      (fun p : ℝ × ℝ =>
        mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y))) :=
    (contMDiff_mulInvariantExp (I := I) (G := G)).comp hrightArg
  exact (f.contMDiff.comp (hleft.mul hright)).contDiff

private theorem contDiff_exponentialVariationGenerator
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) (s : ℝ) :
    ContDiff ℝ ∞ (fun t : ℝ =>
      let Z := X + t • Y
      let B := mulInvariantExp (I := I) (G := G) (s • Z)
      let g := mulInvariantExp (I := I) (G := G) ((-s) • X) * B
      mvfderiv I f g
        (mulInvariantVectorField (tangentAd (I := I) B⁻¹ Y) g)) := by
  let _ : ContMDiffMul I (∞ + 1) G := by
    simpa using (inferInstance : ContMDiffMul I ∞ G)
  let Z : ℝ → E := fun t => @id E (X + t • Y)
  let B : ℝ → G := fun t => mulInvariantExp (I := I) (G := G)
    (s • (show GroupLieAlgebra I G from Z t))
  let g : ℝ → G := fun t => mulInvariantExp (I := I) (G := G) ((-s) • X) * B t
  let V : ℝ → E := fun t => @id E (tangentAd (I := I) (B t)⁻¹ Y)
  have hZ : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, E) ∞ Z := by
    exact (show ContDiff ℝ ∞ Z by fun_prop).contMDiff
  have hsZ : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, E) ∞
      (fun t => s • Z t) := by
    exact (show ContDiff ℝ ∞ (fun t => s • Z t) by fun_prop).contMDiff
  have hB : ContMDiff 𝓘(ℝ, ℝ) I ∞ B := by
    exact (contMDiff_mulInvariantExp (I := I) (G := G)).comp hsZ
  have hBinv : ContMDiff 𝓘(ℝ, ℝ) I ∞ (fun t => (B t)⁻¹) :=
    (contMDiff_inv (I := I) (n := ∞)).comp hB
  have hV : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, E) ∞ V := by
    have hpair : ContMDiff 𝓘(ℝ, ℝ) (I.prod 𝓘(ℝ, E)) ∞
        (fun t => ((B t)⁻¹, @id E Y)) := hBinv.prodMk contMDiff_const
    exact (contMDiff_tangentAd_apply (I := I) (G := G)).comp hpair
  have hg : ContMDiff 𝓘(ℝ, ℝ) I ∞ g := contMDiff_const.mul hB
  have hfield : ContMDiff 𝓘(ℝ, ℝ) I.tangent ∞
      (fun t => (mulInvariantVectorField
        (show GroupLieAlgebra I G from V t) (g t) : TangentBundle I G)) := by
    exact (contMDiff_mulInvariantVectorField_modelSpace (I := I) (G := G) (n := ∞)).comp
      (hV.prodMk hg)
  let df : TangentBundle I G →
      TangentBundle (modelWithCornersSelf ℝ ℝ) ℝ := tangentMap% (f : G → ℝ)
  have hdf : ContMDiff I.tangent (modelWithCornersSelf ℝ ℝ).tangent ∞ df :=
    f.contMDiff.contMDiff_tangentMap (by simp)
  have hsnd : ContMDiff (modelWithCornersSelf ℝ ℝ).tangent
      (modelWithCornersSelf ℝ ℝ) ∞
      (fun p : TangentBundle (modelWithCornersSelf ℝ ℝ) ℝ => p.2) :=
    contMDiff_snd_tangentBundle_modelSpace ℝ (modelWithCornersSelf ℝ ℝ)
  have hresult : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, ℝ) ∞
      (fun t => mvfderiv I f (g t)
        (mulInvariantVectorField (show GroupLieAlgebra I G from V t) (g t))) := by
    have h := hsnd.comp (hdf.comp hfield)
    exact h.congr fun t => rfl
  exact hresult.contDiff

/-- The mixed derivative of the left-trivialized exponential variation is the adjoint orbit of
the varied direction. -/
theorem ContMDiffMap.deriv_timeFDeriv_exponentialVariation
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) (s : ℝ) :
    let F : ℝ × ℝ → ℝ := fun p =>
      f (mulInvariantExp (I := I) (G := G) ((-p.2) • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y)))
    _root_.deriv (timeFDeriv F 0) s =
      mvfderiv I f 1
        (mulInvariantVectorField
          (tangentAd (I := I)
            (mulInvariantExp (I := I) (G := G) ((-s) • X)) Y) 1) := by
  dsimp only
  let F : ℝ × ℝ → ℝ := fun p =>
    f (mulInvariantExp (I := I) (G := G) ((-p.2) • X) *
      mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y)))
  let R : ℝ → ℝ := fun t =>
    let Z := X + t • Y
    let B := mulInvariantExp (I := I) (G := G) (s • Z)
    let g := mulInvariantExp (I := I) (G := G) ((-s) • X) * B
    mvfderiv I f g
      (mulInvariantVectorField (tangentAd (I := I) B⁻¹ Y) g)
  have hF : ContDiff ℝ ∞ F := by
    simpa only [F] using ContMDiffMap.contDiff_exponentialVariation
      (I := I) (G := G) f X Y
  have hspace (t : ℝ) : spatialFDeriv F s t 1 = t * R t := by
    have hemb : HasDerivAt (fun r : ℝ => (t, r)) (0, 1) s :=
      (hasDerivAt_const (x := s) t).prodMk (hasDerivAt_id (𝕜 := ℝ) s)
    have hpartialRaw := (hF.differentiable (by norm_num) (t, s)).hasFDerivAt
      |>.comp_hasDerivAt (f := fun r : ℝ => (t, r)) s hemb
    have hpartial : HasDerivAt (fun r => F (t, r)) (spatialFDeriv F s t 1) s := by
      simpa only [Function.comp_def, spatialFDeriv_apply, zero_smul, one_smul] using hpartialRaw
    have hvariation := ContMDiffMap.hasDerivAt_exponentialVariation
      (I := I) (G := G) f X Y s t
    have hvariation' : HasDerivAt (fun r => F (t, r))
        (mvfderiv I f
          (mulInvariantExp (I := I) (G := G) ((-s) • X) *
            mulInvariantExp (I := I) (G := G) (s • (X + t • Y)))
          (mulInvariantVectorField
            (t • tangentAd (I := I)
              (mulInvariantExp (I := I) (G := G) (s • (X + t • Y)))⁻¹ Y)
            (mulInvariantExp (I := I) (G := G) ((-s) • X) *
              mulInvariantExp (I := I) (G := G) (s • (X + t • Y))))) s := by
      simpa only [F] using hvariation
    rw [hpartial.unique hvariation']
    dsimp only [R]
    rw [mulInvariantVectorField_smul]
    change mfderiv I 𝓘(ℝ, ℝ) f _ (t • _) = _
    rw [map_smul]
    rfl
  have hR : ContDiff ℝ ∞ R := by
    simpa only [R] using contDiff_exponentialVariationGenerator
      (I := I) (G := G) f X Y s
  have hproduct := (hasDerivAt_id (𝕜 := ℝ) 0).mul
    ((hR.differentiable (by simp) 0).hasDerivAt)
  have hspatialDeriv : _root_.deriv (fun t => spatialFDeriv F s t 1) 0 = R 0 := by
    rw [show (fun t => spatialFDeriv F s t 1) = fun t => t * R t by
      funext t; exact hspace t]
    have hfun : id * R = fun t => t * R t := by
      funext t
      rfl
    rw [hfun] at hproduct
    simpa only [id_eq, zero_mul, one_mul, add_zero] using hproduct.deriv
  have hFtwo : ContDiff ℝ 2 F :=
    hF.of_le (show ((2 : ℕ∞) : ℕ∞ω) ≤ ((⊤ : ℕ∞) : ℕ∞ω) from
      WithTop.coe_le_coe.mpr le_top)
  have hFmin : ContDiffAt ℝ (minSmoothness ℝ 2) F (0, s) := by
    simpa using hFtwo.contDiffAt
  have hmixed := deriv_spatialFDeriv_apply (F := F) (x := s) (w := (1 : ℝ)) hFmin
  rw [hspatialDeriv, fderiv_apply_one_eq_deriv] at hmixed
  rw [← hmixed]
  dsimp only [R]
  simp only [zero_smul, add_zero]
  have hneg : mulInvariantExp (I := I) (G := G) ((-s) • X) =
      (mulInvariantExp (I := I) (G := G) (s • X))⁻¹ := by
    rw [show (-s) • X = -(s • X) by module, mulInvariantExp_neg]
  rw [hneg]
  rw [show X + (0 : ℝ) • Y = X by module, inv_mul_cancel]

/-- Integrating the mixed-variation identity expresses the endpoint variation as the integral of
the adjoint orbit. -/
theorem ContMDiffMap.timeFDeriv_exponentialVariation_one
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) :
    let F : ℝ × ℝ → ℝ := fun p =>
      f (mulInvariantExp (I := I) (G := G) ((-p.2) • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y)))
    timeFDeriv F 0 1 = ∫ s in (0 : ℝ)..1,
      mvfderiv I f 1
        (mulInvariantVectorField
          (tangentAd (I := I)
            (mulInvariantExp (I := I) (G := G) ((-s) • X)) Y) 1) := by
  dsimp only
  let F : ℝ × ℝ → ℝ := fun p =>
    f (mulInvariantExp (I := I) (G := G) ((-p.2) • X) *
      mulInvariantExp (I := I) (G := G) (p.2 • (X + p.1 • Y)))
  let q : ℝ → ℝ := timeFDeriv F 0
  let r : ℝ → ℝ := fun s =>
    mvfderiv I f 1
      (mulInvariantVectorField
        (tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) ((-s) • X)) Y) 1)
  have hF : ContDiff ℝ ∞ F := by
    simpa only [F] using ContMDiffMap.contDiff_exponentialVariation
      (I := I) (G := G) f X Y
  have hqdiff : Differentiable ℝ q := by
    have hDF : ContDiff ℝ 1 (fderiv ℝ F) :=
      hF.fderiv_right (m := 1)
        (show ((1 + 1 : ℕ∞) : ℕ∞ω) ≤ ((⊤ : ℕ∞) : ℕ∞ω) from
          WithTop.coe_le_coe.mpr le_top)
    have hemb : ContDiff ℝ 1 (fun s : ℝ => ((0 : ℝ), s)) := by fun_prop
    have happ := (hDF.comp hemb).clm_apply
      (show ContDiff ℝ 1 (fun _ : ℝ => ((1 : ℝ), (0 : ℝ))) from contDiff_const)
    have happ' : ContDiff ℝ 1
        (fun s : ℝ => fderiv ℝ F (0, s) (1, 0)) := by
      simpa only [Function.comp_apply] using happ
    have hqfun : q = fun s : ℝ => fderiv ℝ F (0, s) (1, 0) := by
      funext s
      simp only [q, timeFDeriv_apply]
    rw [hqfun]
    exact happ'.differentiable (by norm_num)
  have hrcont : Continuous r := by
    let γ : ℝ → G := fun s =>
      mulInvariantExp (I := I) (G := G) ((-s) • X)
    let V : ℝ → E := fun s => @id E (tangentAd (I := I) (γ s) Y)
    have harg : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, E) ∞
        (fun s : ℝ => @id E ((-s) • X)) := by
      exact (show ContDiff ℝ ∞ (fun s : ℝ => @id E ((-s) • X)) by
        fun_prop).contMDiff
    have hγ : ContMDiff 𝓘(ℝ, ℝ) I ∞ γ :=
      (contMDiff_mulInvariantExp (I := I) (G := G)).comp harg
    have hV : ContMDiff 𝓘(ℝ, ℝ) 𝓘(ℝ, E) ∞ V := by
      have hpair : ContMDiff 𝓘(ℝ, ℝ) (I.prod 𝓘(ℝ, E)) ∞
          (fun s => (γ s, @id E Y)) := hγ.prodMk contMDiff_const
      exact (contMDiff_tangentAd_apply (I := I) (G := G)).comp hpair
    have hVcont : Continuous V := hV.continuous
    have hrEq : r = fun s => @id ℝ ((mvfderiv I f 1) (V s)) := by
      funext s
      simp only [r, V, γ, mulInvariantVectorField_one]
      with_unfolding_all rfl
    rw [hrEq]
    exact (mvfderiv I f 1).continuous.comp hVcont
  have hderiv (s : ℝ) : HasDerivAt q (r s) s := by
    apply (hqdiff s).hasDerivAt.congr_deriv
    simpa only [q, r] using
      ContMDiffMap.deriv_timeFDeriv_exponentialVariation
        (I := I) (G := G) f X Y s
  have hqzero : q 0 = 0 := by
    have hemb : HasDerivAt (fun t : ℝ => (t, (0 : ℝ))) (1, 0) 0 :=
      (hasDerivAt_id (𝕜 := ℝ) 0).prodMk (hasDerivAt_const (x := 0) 0)
    have hpartialRaw := (hF.differentiable (by norm_num) (0, 0)).hasFDerivAt
      |>.comp_hasDerivAt (f := fun t : ℝ => (t, (0 : ℝ))) 0 hemb
    have hpartial : HasDerivAt (fun t => F (t, 0)) (q 0) 0 := by
      simpa only [q, timeFDeriv_apply, Function.comp_def] using hpartialRaw
    have hconst : HasDerivAt (fun t => F (t, 0)) 0 0 := by
      have hfun : (fun t => F (t, 0)) = fun _ : ℝ => f (1 : G) := by
        funext t
        simp only [F, neg_zero, zero_smul, mulInvariantExp_zero, one_mul]
      rw [hfun]
      exact hasDerivAt_const (x := (0 : ℝ)) (f (1 : G))
    exact hpartial.unique hconst
  have hFTC := intervalIntegral.integral_eq_sub_of_hasDerivAt
    (a := (0 : ℝ)) (b := 1) (f := q) (f' := r)
    (fun s _hs => hderiv s) (hrcont.intervalIntegrable 0 1)
  rw [hqzero, sub_zero] at hFTC
  exact hFTC.symm

end TauCeti.Lie

