/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Analysis.Calculus.ParametricFDeriv
public import TauCeti.Geometry.Lie.Exponential.Smoothness
public import TauCeti.Geometry.Lie.RightInvariantVectorField
public import TauCeti.Geometry.Lie.Tangent.LieEquiv
import TauCeti.Geometry.Lie.Interior

/-!
# Commutation of left- and right-invariant vector fields

This file proves that left- and right-invariant differentiation commute. The proof uses Clairaut
symmetry for a smooth scalar function evaluated on two multiplied exponential lines, then uses
the tangent-vector/point-derivation equivalence to identify the vector-field bracket.

This supplies a prerequisite for Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `mvfderiv_mulInvariant_mulRightInvariant_commute`: left- and right-invariant scalar
  differentiation commute at the identity.
* `mlieBracket_mulRightInvariant_mulInvariant_one`: the corresponding vector-field bracket
  vanishes at the identity.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The infinitesimal adjoint".
-/

public section

noncomputable section

namespace TauCeti.Lie

open Manifold VectorField
open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G]

attribute [local instance] LieGroup.minSmoothnessThree

local instance lieGroupBoundarylessManifold : BoundarylessManifold I G where
  isInteriorPoint' g :=
    ContMDiffMul.isInteriorPoint (I := I) (n := ∞) (by simp) g

/-- The exponential line generated by `X` has initial velocity `X`. -/
theorem hasMFDerivAt_mulInvariantExp_smul (X : GroupLieAlgebra I G) :
    HasMFDerivAt 𝓘(ℝ, ℝ) I
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) 0
      ((1 : ℝ →L[ℝ] ℝ).smulRight X) := by
  have hcurve := isMIntegralCurve_mulInvariantIntegralCurve
    (I := I) (G := G) X (1 : G) 0
  have hzero : mulInvariantIntegralCurve (I := I) (G := G) X 1 0 = 1 :=
    mulInvariantIntegralCurve_zero X 1
  rw [hzero, mulInvariantVectorField_one] at hcurve
  have hfun : (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) =
      mulInvariantIntegralCurve (I := I) (G := G) X 1 := by
    funext t
    rw [mulInvariantExp_smul]
  rw [hfun]
  exact hcurve

/-- Differentiating a smooth scalar function along an exponential line gives its directional
derivative at the identity. -/
theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul {f : G → ℝ}
    {f' : TangentSpace I (1 : G) →L[ℝ] ℝ}
    (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f 1 f') (X : GroupLieAlgebra I G) :
    HasDerivAt (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X))) (f' X) 0 := by
  have hcurve := isMIntegralCurve_mulInvariantIntegralCurve
    (I := I) (G := G) X (1 : G) 0
  have hf0 : HasMFDerivAt I 𝓘(ℝ, ℝ) f
      (mulInvariantIntegralCurve (I := I) (G := G) X 1 0) f' := by
    rw [mulInvariantIntegralCurve_zero]
    exact hf
  have hcomp := hf0.comp 0 hcurve
  have hzero : mulInvariantIntegralCurve (I := I) (G := G) X 1 0 = 1 :=
    mulInvariantIntegralCurve_zero X 1
  rw [hzero, mulInvariantVectorField_one] at hcomp
  have hfun : (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X))) =
      f ∘ mulInvariantIntegralCurve (I := I) (G := G) X 1 := by
    funext t
    rw [mulInvariantExp_smul]
    rfl
  rw [hfun]
  have hF : HasFDerivAt (f ∘ mulInvariantIntegralCurve (I := I) (G := G) X 1)
      (f'.comp ((1 : ℝ →L[ℝ] ℝ).smulRight X)) 0 := hcomp.hasFDerivAt
  simpa only [ContinuousLinearMap.comp_apply, ContinuousLinearMap.smulRight_apply,
    one_apply_eq_self, one_smul] using hF.hasDerivAt

/-- Differentiating after left multiplication gives the left-invariant directional derivative. -/
theorem HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul {f : G → ℝ} {g : G}
    {f' : TangentSpace I g →L[ℝ] ℝ} (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f g f')
    (Y : GroupLieAlgebra I G) :
    HasDerivAt
      (fun t : ℝ => f (g * mulInvariantExp (I := I) (G := G) (t • Y)))
      (f' (mulInvariantVectorField Y g)) 0 := by
  have hmul := (contMDiffAt_mul_left (I := I) (n := ∞) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, ℝ) f (g * 1) f' := by
    rw [mul_one]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hcomp Y
  change HasDerivAt _ (f' ((mfderiv I I (fun x : G => g * x) 1) Y)) 0
  convert h using 1 <;> rfl

/-- Differentiating after right multiplication gives the right-invariant directional derivative. -/
theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul {f : G → ℝ} {g : G}
    {f' : TangentSpace I g →L[ℝ] ℝ} (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f g f')
    (X : GroupLieAlgebra I G) :
    HasDerivAt
      (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X) * g))
      (f' (mulRightInvariantVectorField X g)) 0 := by
  have hmul := (contMDiffAt_mul_right (I := I) (n := ∞) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, ℝ) f (1 * g) f' := by
    rw [one_mul]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hcomp X
  rw [mulRightInvariantVectorField_apply]
  convert h using 1 <;> rfl

/-- A smooth scalar function evaluated on two multiplied exponential lines is smooth in both
parameters. -/
theorem ContMDiffMap.contDiff_comp_mulInvariantExp_mul_mulInvariantExp
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) :
    ContDiff ℝ ∞ (fun p : ℝ × ℝ =>
      f (mulInvariantExp (I := I) (G := G) (p.1 • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • Y))) := by
  have hX : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) X
  have hY : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • Y)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) Y
  have hMprod : ContMDiff (𝓘(ℝ, ℝ).prod 𝓘(ℝ, ℝ)) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) :=
    (hX.comp contMDiff_fst).mul (hY.comp contMDiff_snd)
  have hM : ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) := by
    rw [modelWithCornersSelf_prod, ← chartedSpaceSelf_prod]
    exact hMprod
  exact (f.contMDiff.comp hM).contDiff

/-- Left and right invariant differentiation commute at the identity. This is Clairaut symmetry
for the two-parameter map `(s, t) ↦ exp(sX) exp(tY)`. -/
theorem mvfderiv_mulInvariant_mulRightInvariant_commute
    (f : C^∞⟮I, G; ℝ⟯) (X Y : GroupLieAlgebra I G) :
    mvfderiv I (fun g => mvfderiv I f g (mulInvariantVectorField Y g)) 1 X =
      mvfderiv I (fun g => mvfderiv I f g (mulRightInvariantVectorField X g)) 1 Y := by
  change mfderiv I 𝓘(ℝ, ℝ)
      (fun g => mvfderiv I f g (mulInvariantVectorField Y g)) 1 X =
    mfderiv I 𝓘(ℝ, ℝ)
      (fun g => mvfderiv I f g (mulRightInvariantVectorField X g)) 1 Y
  let γX : ℝ → G := fun t => mulInvariantExp (I := I) (G := G) (t • X)
  let γY : ℝ → G := fun t => mulInvariantExp (I := I) (G := G) (t • Y)
  let F : ℝ × ℝ → ℝ := fun p => f (γX p.1 * γY p.2)
  have hF : ContDiff ℝ 2 F :=
    (ContMDiffMap.contDiff_comp_mulInvariantExp_mul_mulInvariantExp f X Y).of_le
      (show ((2 : ℕ∞) : ℕ∞ω) ≤ ((⊤ : ℕ∞) : ℕ∞ω) from
        WithTop.coe_le_coe.mpr le_top)
  have hspace (t : ℝ) : spatialFDeriv F 0 t 1 =
      mvfderiv I f (γX t) (mulInvariantVectorField Y (γX t)) := by
    have hemb : HasDerivAt (fun s : ℝ => (t, s)) (0, 1) 0 :=
      (hasDerivAt_const (x := 0) t).prodMk (hasDerivAt_id (𝕜 := ℝ) 0)
    have hpartialRaw := (hF.differentiable (by norm_num) (t, 0)).hasFDerivAt
      |>.comp_hasDerivAt 0 hemb
    have hpartial : HasDerivAt (fun s => F (t, s)) (spatialFDeriv F 0 t 1) 0 := by
      simpa only [Function.comp_def, spatialFDeriv_apply, zero_smul, one_smul] using hpartialRaw
    have hfAt := f.contMDiff.mdifferentiable (by simp) (γX t) |>.hasMFDerivAt
    have hdirection := HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul hfAt Y
    have hdirection' : HasDerivAt (fun s => F (t, s))
        (mvfderiv I f (γX t) (mulInvariantVectorField Y (γX t))) 0 := by
      convert hdirection using 1
      all_goals rfl
    exact hpartial.unique hdirection'
  have htime (s : ℝ) : timeFDeriv F 0 s =
      mvfderiv I f (γY s) (mulRightInvariantVectorField X (γY s)) := by
    have hemb : HasDerivAt (fun t : ℝ => (t, s)) (1, 0) 0 :=
      (hasDerivAt_id (𝕜 := ℝ) 0).prodMk (hasDerivAt_const (x := 0) s)
    have hpartialRaw := (hF.differentiable (by norm_num) (0, s)).hasFDerivAt
      |>.comp_hasDerivAt 0 hemb
    have hpartial : HasDerivAt (fun t => F (t, s)) (timeFDeriv F 0 s) 0 := by
      simpa only [Function.comp_def, timeFDeriv_apply, zero_smul, one_smul] using hpartialRaw
    have hfAt := f.contMDiff.mdifferentiable (by simp) (γY s) |>.hasMFDerivAt
    have hdirection := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul hfAt X
    have hdirection' : HasDerivAt (fun t => F (t, s))
        (mvfderiv I f (γY s) (mulRightInvariantVectorField X (γY s))) 0 := by
      convert hdirection using 1
      all_goals rfl
    exact hpartial.unique hdirection'
  have hFmin : ContDiffAt ℝ (minSmoothness ℝ 2) F (0, 0) := by
    simpa using hF.contDiffAt
  have hmixed := deriv_spatialFDeriv_apply (F := F) (x := (0 : ℝ)) (w := (1 : ℝ)) hFmin
  have hspaceFun : (fun t => spatialFDeriv F 0 t 1) =
      fun t => mvfderiv I f (γX t) (mulInvariantVectorField Y (γX t)) := by
    funext t
    exact hspace t
  have htimeFun : timeFDeriv F 0 =
      fun s => mvfderiv I f (γY s) (mulRightInvariantVectorField X (γY s)) := by
    funext s
    exact htime s
  rw [hspaceFun, htimeFun, fderiv_apply_one_eq_deriv] at hmixed
  let LYf : C^∞⟮I, G; ℝ⟯ :=
    ⟨fun g => mvfderiv I f g (mulInvariantVectorField Y g),
      contMDiff_mvfderiv_mulInvariantVectorField Y f⟩
  let RXf : C^∞⟮I, G; ℝ⟯ :=
    ⟨fun g => mvfderiv I f g (mulRightInvariantVectorField X g),
      contMDiff_mvfderiv_mulRightInvariantVectorField X f⟩
  have hLYmf := LYf.contMDiff.mdifferentiable (by simp) 1 |>.hasMFDerivAt
  have hLY := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hLYmf X
  have hRXmf := RXf.contMDiff.mdifferentiable (by simp) 1 |>.hasMFDerivAt
  have hRX := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hRXmf Y
  change HasDerivAt
    (fun t => mvfderiv I f (γX t) (mulInvariantVectorField Y (γX t)))
    (mfderiv I 𝓘(ℝ, ℝ) LYf 1 X) 0 at hLY
  change HasDerivAt
    (fun t => mvfderiv I f (γY t) (mulRightInvariantVectorField X (γY t)))
    (mfderiv I 𝓘(ℝ, ℝ) RXf 1 Y) 0 at hRX
  have hLYderiv : deriv
      (fun t => mvfderiv I f (γX t) (mulInvariantVectorField Y (γX t))) 0 =
      mfderiv I 𝓘(ℝ, ℝ) LYf 1 X := by
    simpa only [γX, LYf] using hLY.deriv
  have hRXderiv : deriv
      (fun t => mvfderiv I f (γY t) (mulRightInvariantVectorField X (γY t))) 0 =
      mfderiv I 𝓘(ℝ, ℝ) RXf 1 Y := by
    simpa only [γY, RXf] using hRX.deriv
  rw [hLYderiv, hRXderiv] at hmixed
  change mfderiv I 𝓘(ℝ, ℝ) LYf 1 X = mfderiv I 𝓘(ℝ, ℝ) RXf 1 Y
  exact hmixed

/-- Right- and left-invariant vector fields commute at the identity. -/
theorem mlieBracket_mulRightInvariant_mulInvariant_one
    (X Y : GroupLieAlgebra I G) :
    mlieBracket I (mulRightInvariantVectorField X) (mulInvariantVectorField Y) 1 = 0 := by
  apply tangentToPointDerivation_injective (I := I) (1 : G)
  rw [map_zero]
  ext f
  change mvfderiv I f 1
    (mlieBracket I (mulRightInvariantVectorField X) (mulInvariantVectorField Y) 1) = 0
  have hbridge := mvfderiv_mlieBracket
    (f := (f : G → ℝ))
    (V := mulRightInvariantVectorField X)
    (W := mulInvariantVectorField Y)
    (x := (1 : G))
    (f.contMDiff.contMDiffAt.of_le (show
      ((2 : ℕ∞) : ℕ∞ω) ≤ ((⊤ : ℕ∞) : ℕ∞ω) from
        WithTop.coe_le_coe.mpr le_top))
    (by simp)
    ((contMDiff_mulRightInvariantVectorField_infty X).mdifferentiable
      (by simp)).mdifferentiableAt
    ((contMDiff_mulInvariantVectorField_infty Y).mdifferentiable
      (by simp)).mdifferentiableAt
  have hright : mulRightInvariantVectorField X (1 : G) = X := by
    exact mulRightInvariantVectorField_one X
  rw [hbridge, hright, mulInvariantVectorField_one]
  let F : C^∞⟮I, G; ℝ⟯ := f
  have hcomm := mvfderiv_mulInvariant_mulRightInvariant_commute F X Y
  apply sub_eq_zero.mpr
  convert hcomm using 1
  all_goals rfl

end TauCeti.Lie
